#!/usr/bin/env bash

#set -eu

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${BASEDIR}/install.conf.json"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"
git config --global alias.dsf '!f() { [ -z "$GIT_PREFIX" ] || cd "$GIT_PREFIX" '\
    '&& git diff --color "$@" | diff-so-fancy  | less --tabs=4 -RFX; }; f'
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
